require "modules/globalData"
require "modules/windows"
require "modules/resize"
require "modules/volume"
require "modules/reload"
require "modules/test"
-- require "modules/wifi"
-- require "modules/timer"
