---- 1/9
--one = { prefix = hyper, key = "1", message = "1/9" },
---- 2/9
--two = { prefix = hyper, key = "2", message = "2/9" },
---- 3/9
--three = { prefix = hyper, key = "3", message = "3/9" },
---- 4/9
--four = { prefix = hyper, key = "4", message = "4/9" },
---- 5/9
--five = { prefix = hyper, key = "5", message = "5/9" },
---- 6/9
--six = { prefix = hyper, key = "6", message = "6/9" },
---- 7/9
--seven = { prefix = hyper, key = "7", message = "7/9" },
---- 8/9
--eight = { prefix = hyper, key = "8", message = "8/9" },
---- 9/9
--nine = { prefix = hyper, key = "9", message = "9/9" },